### ISSUE TITLE
Prevent traversability issues for `corridors` map type

### ISSUE THREAD

**Issue by ElnuDev** [ElnuDev/hebi#5]
Currently, the `corridors` map type only inserts passageways in columns when they fill up the entire grid height. However, this is not the only scenario that will divide the map into multiple isolated rooms. More commonly, with an offset top or bottom corridor, two walls just a single x-coordinate appart that sum (but aren't individually) to more than the window height will touch, blocking the path. The following `config.toml` file will cause this issue:

```TOML
[map]
type = "corridors"
width = 51
height = 19
corridor_width = 3
corridor_height = 14
top_corridor_offset = 1
bottom_corridor_offset = 0
wall_variance = 0.6
```

![Screenshot from 2021-08-29 17-48-59](https://user-images.githubusercontent.com/9874955/131271307-26d683f3-5f22-467d-ae95-4f44aeee549c.png)

This shouldn't be too hard to fix, but it might be a bit fiddly. It isn't high priority.
